/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as ReportsIndexRouteImport } from './routes/reports.index'
import { Route as ReportsReportIdRouteImport } from './routes/reports.$reportId'
import { Route as SupportTicketsIndexRouteImport } from './routes/support-tickets.index'
import { Route as SupportTicketsTicketIdRouteImport } from './routes/support-tickets.$ticketId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsReportIdRoute = ReportsReportIdRouteImport.update({
  id: '/reports/$reportId',
  path: '/reports/$reportId',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportTicketsIndexRoute = SupportTicketsIndexRouteImport.update({
  id: '/support-tickets/',
  path: '/support-tickets/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportTicketsTicketIdRoute = SupportTicketsTicketIdRouteImport.update({
  id: '/support-tickets/$ticketId',
  path: '/support-tickets/$ticketId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/reports/$reportId': typeof ReportsReportIdRoute
  '/support-tickets/$ticketId': typeof SupportTicketsTicketIdRoute
  '/reports/': typeof ReportsIndexRoute
  '/support-tickets/': typeof SupportTicketsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/reports/$reportId': typeof ReportsReportIdRoute
  '/support-tickets/$ticketId': typeof SupportTicketsTicketIdRoute
  '/reports': typeof ReportsIndexRoute
  '/support-tickets': typeof SupportTicketsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/reports/$reportId': typeof ReportsReportIdRoute
  '/support-tickets/$ticketId': typeof SupportTicketsTicketIdRoute
  '/reports/': typeof ReportsIndexRoute
  '/support-tickets/': typeof SupportTicketsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/health'
    | '/reports/$reportId'
    | '/support-tickets/$ticketId'
    | '/reports/'
    | '/support-tickets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/health'
    | '/reports/$reportId'
    | '/support-tickets/$ticketId'
    | '/reports'
    | '/support-tickets'
  id:
    | '__root__'
    | '/'
    | '/api/health'
    | '/reports/$reportId'
    | '/support-tickets/$ticketId'
    | '/reports/'
    | '/support-tickets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ReportsReportIdRoute: typeof ReportsReportIdRoute
  SupportTicketsTicketIdRoute: typeof SupportTicketsTicketIdRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
  SupportTicketsIndexRoute: typeof SupportTicketsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/$reportId': {
      id: '/reports/$reportId'
      path: '/reports/$reportId'
      fullPath: '/reports/$reportId'
      preLoaderRoute: typeof ReportsReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support-tickets/': {
      id: '/support-tickets/'
      path: '/support-tickets'
      fullPath: '/support-tickets/'
      preLoaderRoute: typeof SupportTicketsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support-tickets/$ticketId': {
      id: '/support-tickets/$ticketId'
      path: '/support-tickets/$ticketId'
      fullPath: '/support-tickets/$ticketId'
      preLoaderRoute: typeof SupportTicketsTicketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiHealthRoute: ApiHealthRoute,
  ReportsReportIdRoute: ReportsReportIdRoute,
  SupportTicketsTicketIdRoute: SupportTicketsTicketIdRoute,
  ReportsIndexRoute: ReportsIndexRoute,
  SupportTicketsIndexRoute: SupportTicketsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
