/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as ApiNavigationSessionRouteImport } from './routes/api.navigation-session'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNavigationSessionRoute = ApiNavigationSessionRouteImport.update({
  id: '/api/navigation-session',
  path: '/api/navigation-session',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/health': typeof ApiHealthRoute
  '/api/navigation-session': typeof ApiNavigationSessionRoute
  '/events/$slug': typeof EventsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/health': typeof ApiHealthRoute
  '/api/navigation-session': typeof ApiNavigationSessionRoute
  '/events/$slug': typeof EventsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/health': typeof ApiHealthRoute
  '/api/navigation-session': typeof ApiNavigationSessionRoute
  '/events/$slug': typeof EventsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/login' | '/api/health' | '/api/navigation-session' | '/events/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/login' | '/api/health' | '/api/navigation-session' | '/events/$slug'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/api/health'
    | '/api/navigation-session'
    | '/events/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiNavigationSessionRoute: typeof ApiNavigationSessionRoute
  EventsSlugRoute: typeof EventsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/navigation-session': {
      id: '/api/navigation-session'
      path: '/api/navigation-session'
      fullPath: '/api/navigation-session'
      preLoaderRoute: typeof ApiNavigationSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiNavigationSessionRoute: ApiNavigationSessionRoute,
  EventsSlugRoute: EventsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
